0913과제
nhnacademyGroup5/IntroductiontoProgramming pull request #31
Opened 2023-09-13 16:07 UTC by 927138

2023-09-13 16:35 UTC, xixvivji approved these changes

2023-09-13 19:40 UTC, seong1542 commented on KimTaeSu/9:12/Exercises3 복사본.java
> +        return this.messageText + "NumberToCall : " + getNumberToCall() + "\n" + "NumberOfSender : "
불필요한 요소를 빼고 다시 수정해보셨군요 좋습니다.

2023-09-13 19:41 UTC, seong1542 commented on jiwon/Unit3/BookExample.java
> +        // System.out.println(b2 + " " + b3);
필요없는 부분은 그냥 지워주세요.

2023-09-13 19:47 UTC, seong1542 commented on jiyh/ch5/Date.java
> +        if(month % 2 == 1){
LocalDate를 이용하여 문제를 풀어보는건 어떨까요? LocalDate를 사용하게 되면 매달 마지막날이 몇일인지를 계산할 필요가 없어집니다.

2023-09-13 19:48 UTC, seong1542 commented on jiyh/ch5/DateTest.java
> +        Date date1 = new Date(1999, 11, 27);
현재는 Date라는 클래스를 이용하기 위해서 이렇게 작성하였지만, 이렇게 이용해보았으니 다르게도 작성해봅시다.
LocalDate를 이용하여 Date에서 이용하셨던 것과 결과값이 같도록 작성해보세요

2023-09-13 19:50 UTC, seong1542 commented on jiyh/ch5/DateTest.java
> +        System.out.println(date1.getDay());
println을 세번하셨는데 System.out.println을 한번만 사용하고, 결과값이 같도록 다시 재작성해보세요.

2023-09-14 00:15 UTC, seong1542 commented on jiyh/ch5/Exercise2.java
> +            // System.out.println("irregular");
불필요한 코드라고 생각된다면 지워주세요.

2023-09-14 00:17 UTC, seong1542 commented on jiyh/ch5/Exercise1.java
> +        if(g > 40) System.out.println("extra strong liquor");
if else말고 다른 방법은 없을까요? if else 외에 다른 방식으로 재작성해보세요.

2023-09-14 00:26 UTC, seong1542 commented on jiyh/ch5/Exercise5.java
> +public class Exercise5 {
exercise 6번 문제인것 같습니다?

2023-09-14 00:47 UTC, seong1542 commented on jiyh/ch5/Exercise5.java
> +        String[] str = sc.nextLine().split(" ");
split을 이용하신걸 보니 여러 단어가 존재하였을 때를 생각하신 것 같습니다. 하지만 아래 로직을 살펴보면 한 단어만 처리가 가능하도록 되어있죠?
그리고 charAt을 사용하여 처리한 것도 좋지만 다른 방법을 사용해보기 위해 변형 문제를 드리겠습니다.

1) 단어에 a, b, c가 포함되었을 때 "YES"가 출력되고, 그외 단어는 NO가 나오도록 해주세요.
2) 끝글자를 확인할 때 사용되는 함수가 또 있습니다. 찾아서 사용해보세요.

2023-09-14 00:54 UTC, seong1542 commented on jiyh/ch5/Triangle.java
> +    private void sort(int value[]){
1) 버블정렬을 선택하셨군요. 정렬에는 종류가 많죠. 그 중 버블정렬을 선택하신 이유는 무엇인가요? comment로 달아주세요.

2) 버블 정렬 외에도 다른 정렬도 할 수 있죠. 선택정렬, 삽입정렬, 병합정렬 3가지 구현해보시고, 어떤 정렬이 가장 빠른지 체크해보세요.

2023-09-14 00:56 UTC, seong1542 commented on jiyh/ch5/TriangleEx.java
> +        System.out.println("Longest : " + angle.getLongest());
이렇게 print하는것도 하나의 메소드로 분리해보시는건 어떨까요?

2023-09-14 01:39 UTC, seong1542 commented on jiyh/ch6/Messages.java
> +            sb.append(" " + st.nextToken());
string builder에서 문자열을 append하는데, +연산자를 사용하셨네요? 수정해봅시다.

2023-09-14 02:12 UTC, 927138 commented on jiyh/ch5/Triangle.java
> +    private void sort(int value[]){
버블정렬을 사용한 이유는 value.length 값이 최대가 3으로 고정이 되어있어 합병정렬을 사용해도 처리시간의 차이는 크게 차이가 나지 않는다고 판단하여 버블정렬을 사용했습니다.

2023-09-14 03:38 UTC, seong1542 commented on jiyh/ch6/Messages.java
> +            if(ch == 'A' || ch == 'E' || ch == 'I' || ch == 'O' || ch == 'U') {
추가문제 드릴게요.

현재는 각 문자를 체크해서 해당 문자들을 만났을때 지우는 방식으로 작성하셨습니다.
문제를 바꿔서 A, E, I, O, U 문자를 만났을 때 빈칸으로 바꿔서 작성해보세요.

2023-09-14 03:41 UTC, seong1542 commented on jiyh/ch6/Messages.java
> +    public void eliminationvowel(){
메소드명 규칙 지켜주세요.

2023-09-14 03:43 UTC, seong1542 commented on jiyh/ch6/staticMethod.java
> +    public static int chisEmtpy(String str, char ch){
해당 메소드는 무엇을 나타내고자 하는 메소드인가요? 메소드명 정하실때 팀원들이 확인하고 바로 이해할 수 있도록 하는 것이 좋습니다.

2023-09-14 03:44 UTC, seong1542 commented on jiyh/ch7/staticMethod.java
> +    public static int[] Intersection(int[] A, int[] B){
전체적으로 클래스 명명규칙, 메소드 명명규칙에 대해 알아보셔야 할 것 같습니다. 이건 규칙이기 때문에 꼭 숙지하시고 넘어가셨으면 좋겠습니다.

2023-09-14 03:44 UTC, seong1542 commented on jiyh/ch7/staticMethod.java
> +        // 정방행렬만 가능
불필요하다고 생각되는 코드는 올리지 않고, 지워주세요.

2023-09-14 03:48 UTC, seong1542 commented on jiyh/ch7/staticMethod.java
> +    public static double[][] transposeMatrix(double[][] M){
변수명 규칙도 살펴봐주세요. 그리고 변수명 정하실 때 한번 더 고민해가면서 정해주시면 좋을 것 같습니다. 전체적으로 코드에 변수명이 a, b, x, ...등 으로 작성하시는 경우가 있습니다. 물론 아직 우리 단계에서 큰 필요성을 못느끼실 수 있지만, 지금부터 조금씩 노력해봅시다.

2023-09-14 03:55 UTC, seong1542 requested changes
다시 수정하시고 올려주세요. 확인 후 승인하겠습니다.

과제를 하면서 갈 수록 더 깔끔하게 쓰시려고 노력하시는 것 같습니다. 하지만 변수명, 메소드명, 클래스명...등의 규칙들을 아직 숙지하지 못하신 것 같습니다. 전체적으로 수정하시는게 좋을 것 같고, 특히 변수명 작성하실때 a, b, s,...등 의미 없이 지어지는 변수들이 많은 것 같습니다. 이름 짓는게 제일 어려워요. 팀프로젝트를 진행할 때도 지금과 같이 습관적으로 a,b.. 이렇게 작성할 수 있습니다. 연습하는 의미로 생각하시면서 더 나은 변수명이 있을지 생각해보세요.

그리고 전체적으로 비슷한 흐름으로 코드가 작성되고 있는 것 같습니다. 반복적으로 Scanner, charAt등.. 사용하고 있어요. 물론 무조건 사용해야할때가 있을겁니다. 하지만 굳이 이용하지 않아도 다른 함수로 이용할 수 있는게 있는지 찾아가보시면서 하는게 좋을 것 같아요. 입력도 Scanner만 가능한게 아니잖아요? 형변환이라던지.. 자꾸 다른 방식으로 접근하면서 작성해보시면 연습에 도움이 될 것 같습니다. 혹시 작성하시면서 도저히 찾아도 나오지 않거나 아이디어가 필요하시면 코멘트 달아주세요.

2023-09-15 02:00 UTC, seong1542 approved these changes

2023-09-15 02:57 UTC, merged